// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/bg.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  maxstream: require('../Images/menu/faces.png'),
  menu: require('../Images/menu/menu.png'),
  menufaces: require('../Images/menu/faces.png'),
  // menufaces: require('../Images/menu/menu.png'),
  drawerCover: require('../Images/drawer-cover.png'),
  drawerImage: require('../Images/logo-kitchen-sink.png'),
  launchscreenBg: require('../Images/launchscreen-bg.png'),
  launchscreenLogo: require('../Images/logo-kitchen-sink.png'),
  renunganPagiIcon: require('../Images/renunganPagiIcon.png'),
  sekolahsabatIcon: require('../Images/sekolahsabatIcon.png'),
  facebookWhite: require('../Images/facebook_white.png'),
  twitterWhite: require('../Images/twitter-white.png'),

  pratik: require('../Images/contacts/pratik.png'),
  sanket: require('../Images/contacts/sanket.png'),
  megha: require('../Images/contacts/megha.png'),
  atul: require('../Images/contacts/atul.png'),
  saurabh: require('../Images/contacts/saurabh.png'),
  varun: require('../Images/contacts/varun.png'),

  headerBar: require('../Images/header_bar.png'),
  hamburgerMenu: require('../Images/menu/hamburger_menu.png'),
  backWhite: require('../Images/back_white.png'),
  headerHome: require('../Images/home/home.png'),
  searchWhite: require('../Images/search_white/search.png'),
  bg: require('../Images/bg.png'),
  // sendMsgIcon: 0
  sendMsgIcon: require('../Images/send-msg.png')
}

export default images
