// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  maxstream: require('../Images/menu/faces.png'),
  menu: require('../Images/menu/menu.png'),
  menufaces: require('../Images/menu/faces.png'),
  // menufaces: require('../Images/menu/menu.png'),
  drawerCover: require('../Images/drawer-cover.png'),
  drawerImage: require('../Images/logo-kitchen-sink.png'),
  launchscreenBg: require('../Images/launchscreen-bg.png'),
  launchscreenLogo: require('../Images/logo-kitchen-sink.png'),
  renunganPagiIcon: require('../Images/renunganPagiIcon.png'),
  sekolahsabatIcon: require('../Images/sekolahsabatIcon.png'),
}

export default images
