# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PizzaApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # rn_path = '../node_modules/react-native'
  # pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  # pod 'React', path: rn_path, subspecs: [
  # 'Core',
  # 'RCTActionSheet',
  # 'RCTAnimation',
  # 'RCTGeolocation',
  # 'RCTImage',
  # 'RCTLinkingIOS',
  # 'RCTNetwork',
  # 'RCTSettings',
  # 'RCTText',
  # 'RCTVibration',
  # 'RCTWebSocket'
  # ]

  # Pods for PizzaApp
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'


  

  platform :ios, '9.0'
  # pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  # pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  target 'PizzaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PizzaApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PizzaApp-tvOS

  target 'PizzaApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#       if target.name == "React"
#           target.remove_from_project
#       end
#   end
# end
